version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    environment:
      - PORT=8080
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=techeer
      - DB_PASSWORD=secret
      - DB_NAME=hackathon
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=techeer
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=hackathon
    volumes:
      - pg_data_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  db-viewer:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
     - "3000:3000"
    volumes:
     - pgadmin_data_dev:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=test
      - PGADMIN_LISTEN_PORT=3000
    depends_on:
      - db

volumes:
  pg_data_dev:
  pgadmin_data_dev: